### ISSUE TITLE
Missing dependency on package "inflection"

### ISSUE THREAD

**Issue by ali1234** [areebbeigh/profanityfilter#5]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/al/Source/pimodisco/pimodisco/__main__.py", line 6, in <module>
    from pimodisco.filter import filter
  File "/home/al/Source/pimodisco/pimodisco/filter.py", line 4, in <module>
    from profanityfilter import ProfanityFilter
  File "/home/al/.local/lib/python3.5/site-packages/profanityfilter/__init__.py", line 1, in <module>
    from .profanityfilter import *
  File "/home/al/.local/lib/python3.5/site-packages/profanityfilter/profanityfilter.py", line 4, in <module>
    import inflection
```

**Comment by areebbeigh** [comment]
Fixed. Thanks :)
